{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
